[package]
name = "gensokyo-radio"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.3", features = ["full"] }
stream-download = { version = "0.7.2", features = ["reqwest-native-tls"] }
rodio = "0.19.0"
